# Auto-generated by build_script.py during pip/pipx install from git
# This file preserves the git branch name for display in the TUI title bar
# See build_script.py and src/luskctl/tui/app.py for details
BRANCH_NAME = "copilot/sub-pr-125"
