#!/usr/bin/env python3
"""
Poetry build script to preserve git branch information during installation.

This script is invoked by Poetry during the build process (configured via
[tool.poetry.build].script in pyproject.toml). It overwrites the placeholder
_branch_info.py with the actual git branch name when installing from a git
repository.

RATIONALE:
----------
When users install luskctl via `pip install <git-dir>` or `pipx install <git-dir>`,
the installed package loses access to the original git repository. This script
captures the branch information at build time so it can be displayed in the TUI
title bar, helping developers identify which version they're running.

IMPLEMENTATION:
---------------
A placeholder _branch_info.py with BRANCH_NAME = None is checked into the repo.
This ensures the file is always included in the wheel. During pip/pipx install
from a git directory, this script overwrites the placeholder with the actual
branch name.

BEHAVIOR:
---------
- Building from git (non-release): overwrites _branch_info.py with branch name
- Building from tagged release (vX.Y.Z): leaves placeholder unchanged (None)
- Building from non-git source (tarball, etc.): leaves placeholder unchanged (None)

The TUI reads _branch_info.py and displays the branch name if set, otherwise
falls back to live git detection (for development mode) or shows version only.
"""

import subprocess
from pathlib import Path


def _is_tagged_release() -> bool:
    """Check if HEAD is at an exact version tag (vX.Y.Z format).

    Returns True only for commits that are exactly tagged with a version tag,
    indicating an official release. This prevents branch names from appearing
    in release builds.
    """
    try:
        result = subprocess.run(
            ["git", "describe", "--exact-match", "--tags", "HEAD"],
            capture_output=True,
            text=True,
            timeout=1,
        )
        if result.returncode == 0:
            tag = result.stdout.strip()
            # Only consider vX.Y.Z format tags as releases (e.g., v0.3.1, v1.0.0)
            return tag.startswith("v") and len(tag) > 1 and tag[1].isdigit()
    except Exception:
        pass
    return False


def _get_git_branch() -> str | None:
    """Get the current git branch name if we're in a git repository.

    Returns None if:
    - Not in a git repository
    - Git command fails
    - In detached HEAD state (empty branch name)
    """
    try:
        # Check if we're in a git repo
        result = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            capture_output=True,
            text=True,
            timeout=1,
        )
        if result.returncode == 0 and result.stdout.strip() == "true":
            # Get current branch name
            branch_result = subprocess.run(
                ["git", "branch", "--show-current"],
                capture_output=True,
                text=True,
                timeout=1,
            )
            if branch_result.returncode == 0:
                branch = branch_result.stdout.strip()
                return branch if branch else None
    except Exception:
        pass
    return None


def _write_branch_info(branch_name: str) -> None:
    """Overwrite _branch_info.py placeholder with actual branch name.

    This overwrites the placeholder file (BRANCH_NAME = None) with the detected
    branch name, which will be included in the built wheel.
    """
    content = f'''# Auto-generated by build_script.py during pip/pipx install from git
# This file preserves the git branch name for display in the TUI title bar
# See build_script.py and src/luskctl/tui/app.py for details
BRANCH_NAME = "{branch_name}"
'''

    branch_info_path = Path("src/luskctl/_branch_info.py")
    try:
        branch_info_path.write_text(content)
        print(f"build_script.py: Preserved branch information: {branch_name}")
    except Exception as e:
        print(f"build_script.py: Warning: Could not write branch info: {e}")


def build(setup_kwargs: dict) -> None:
    """Poetry build hook entry point.

    Called by Poetry during the build process. Overwrites the _branch_info.py
    placeholder if we're in a git repository on a non-release branch.

    Args:
        setup_kwargs: Dictionary of setup arguments (not modified by this script)
    """
    print("build_script.py: Checking for git branch information...")

    # Skip if this is a tagged release - releases should not show branch names
    if _is_tagged_release():
        print("build_script.py: Tagged release detected, keeping placeholder (None)")
        return

    # Get the current branch name and overwrite placeholder if found
    branch_name = _get_git_branch()
    if branch_name:
        print(f"build_script.py: Detected git branch: {branch_name}")
        _write_branch_info(branch_name)
    else:
        print("build_script.py: Not in a git repository, keeping placeholder (None)")


# Also support direct execution for testing
if __name__ == "__main__":
    build({})
