project:
  id: "uc"
  name: "Ultimate Container"
  security_class: "online"      # agent can push directly to upstream

git:
  upstream_url: "https://gitlab.com/electric-sheep/ultimate-container.git"
  default_branch: "main"

docker:
  base_image: "ubuntu:24.04"
  user_snippet_file: "user.dockerinclude"

ssh:
  key_name: "id_ed25519_uc"
  host_key_dir: "/virt/podman/envs/_ssh-config-uc"

codex:
  host_config_dir: "/virt/podman/envs/_codex-config"
  ui:
    enabled: true

# Default agent for this project (used for Web UI, and potentially CLI in the future).
# Overrides the global config. Can also be set via DEFAULT_AGENT env var or --backend CLI flag.
# Valid values: codex, claude, mistral
# default_agent: claude

# Runtime settings for this project
run:
  # Enable GPU passthrough for this project (per-project only). Default is disabled.
  # Accepts boolean true or string "all" to enable; omitted/false disables.
  # Note: GPU-enabled projects typically require a CUDA/NVIDIA-capable base image.
  # Configure under docker.base_image accordingly.
  # gpus: all
