project:
  id: "cp2k"
  name: "CP2K VM dev"
  security_class: "gatekeeping"

git:
  upstream_url: "https://github.com/cp2k/cp2k.git"
  default_branch: "master"

docker:
  base_image: "nvcr.io/nvidia/nvhpc:25.11-devel-cuda13.0-ubuntu24.04"
  user_snippet_inline: |
    RUN apt-get update && apt-get install -y --no-install-recommends \
          ca-certificates curl gnupg lsb-release software-properties-common \
          build-essential git pkg-config ninja-build openssh-client \
          gcc-14 g++-14 gfortran-14 cmake python3 \
          fypp libopenmpi-dev libopenblas-dev libscalapack-mpi-dev openmpi-bin \
          libhdf5-dev \
        && rm -rf /var/lib/apt/lists/*

    RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140 \
     && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 140 \
     && update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-14 140

run:
  gpus: all

