project:
  id: "alpaka3"
  name: "Alpaka3"
  # Gatekept: tasks can only push to a host-side staging repo, not upstream
  security_class: "gatekeeping"

git:
  # Upstream is intentionally SSH to exercise SSH init when used in online mode.
  # In gatekeeping mode we do NOT expose this inside the container.
  upstream_url: "git@github.com:sliwowitz/alpaka3.git"
  default_branch: "dev"

docker:
  # GPU-capable base image (NVIDIA HPC SDK, CUDA 13, Ubuntu 24.04)
  base_image: "nvcr.io/nvidia/nvhpc:25.9-devel-cuda13.0-ubuntu24.04"
  # This is executed when building the L2 project image
  user_snippet_inline: |
    RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates curl gnupg lsb-release software-properties-common \
        build-essential git pkg-config ninja-build openssh-client \
        gcc-14 g++-14 \
     && rm -rf /var/lib/apt/lists/*

    RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140 \
     && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 140

# No SSH exposure for gatekeeping projects inside the container by default.
# You may still generate keys on the host for mirroring/promotions.
ssh:
  key_name: "id_ed25519_alpaka3"
  # mount_in_gatekeeping: true  # Enable SSH mount in gatekeeping mode

# Gatekeeping mode settings
gatekeeping:
  # Expose the upstream URL as a remote named "external" inside the container.
  expose_external_remote: true

  # Upstream polling - TUI periodically checks if upstream has new commits
  upstream_polling:
    enabled: true           # default: true
    interval_minutes: 5     # default: 5

  # Auto-sync - automatically update gate when upstream changes detected
  auto_sync:
    enabled: false          # default: false (manual sync preferred)
    branches:               # branches to auto-sync (required if enabled)
      - dev

# Runtime settings for this project
run:
  # Enable GPUs for this project
  gpus: all
